### ISSUE TITLE
Error logs vercel

### ISSUE THREAD

**Issue by InstaTechHD** [benjoquilario/animehi-stream#26]
Hi, do you know what might be causing this? 

[11:30:56.864] Running build in Washington, D.C., USA (East) – iad1
[11:30:57.051] Cloning github.com/InstaTechHD/animehi-stream (Branch: master, Commit: fb7a3a5)
[11:30:57.557] Previous build cache not available
[11:30:58.483] Cloning completed: 1.431s
[11:30:59.346] Running "vercel build"
[11:31:00.305] Vercel CLI 35.1.0
[11:31:00.880] Installing dependencies...
[11:31:00.926] bun install v1.1.17 (bb66bba1)
[11:31:00.945] Resolving dependencies
[11:31:00.993] Resolved, downloaded and extracted [2]
[11:31:12.392] Saved lockfile
[11:31:12.392] 
[11:31:12.392] $ prisma generate
[11:31:12.924] Prisma schema loaded from prisma/schema.prisma
[11:31:13.673] 
[11:31:13.674] ✔ Generated Prisma Client (v5.15.0) to ./node_modules/@prisma/client in 229ms
[11:31:13.675] 
[11:31:13.675] Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
[11:31:13.675] ```
[11:31:13.675] import { PrismaClient } from '@prisma/client'
[11:31:13.675] const prisma = new PrismaClient()
[11:31:13.675] ```
[11:31:13.676] or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
[11:31:13.676] ```
[11:31:13.676] import { PrismaClient } from '@prisma/client/edge'
[11:31:13.676] const prisma = new PrismaClient()
[11:31:13.676] ```
[11:31:13.677] 
[11:31:13.677] See other ways of importing Prisma Client: http://pris.ly/d/importing-client
[11:31:13.677] 
[11:31:13.677] ┌─────────────────────────────────────────────────────────────┐
[11:31:13.677] │  Deploying your app to serverless or edge functions?        │
[11:31:13.678] │  Try Prisma Accelerate for connection pooling and caching.  │
[11:31:13.678] │  https://pris.ly/cli/--accelerate                           │
[11:31:13.678] └─────────────────────────────────────────────────────────────┘
[11:31:13.678] 
[11:31:13.860] 
[11:31:13.860] + @ianvs/prettier-plugin-sort-imports@4.2.1
[11:31:13.860] + @tanstack/eslint-plugin-query@5.32.1
[11:31:13.860] + @types/bcrypt@5.0.2
[11:31:13.860] + @types/lodash.chunk@4.2.9
[11:31:13.860] + @typescript-eslint/parser@6.21.0
[11:31:13.861] + autoprefixer@10.4.15
[11:31:13.861] + eslint@8.49.0
[11:31:13.861] + eslint-config-next@13.4.19
[11:31:13.861] + eslint-config-prettier@9.1.0
[11:31:13.861] + eslint-plugin-import@2.29.1
[11:31:13.861] + eslint-plugin-prettier@5.1.3
[11:31:13.861] + eslint-plugin-react@7.34.1
[11:31:13.861] + eslint-plugin-react-hooks@4.6.2
[11:31:13.861] + eslint-plugin-simple-import-sort@12.1.0
[11:31:13.861] + eslint-plugin-tailwindcss@3.15.2
[11:31:13.861] + eslint-plugin-unused-imports@3.2.0
[11:31:13.861] + lodash.chunk@4.2.0
[11:31:13.861] + postcss@8.4.29
[11:31:13.861] + prettier@3.2.5
[11:31:13.861] + prettier-plugin-tailwindcss@0.5.14
[11:31:13.861] + prisma@5.15.0
[11:31:13.862] + tailwindcss@3.3.3
[11:31:13.862] + @auth/core@0.16.1
[11:31:13.862] + @auth/prisma-adapter@2.2.0
[11:31:13.862] + @consumet/extensions@1.5.6
[11:31:13.862] + @hookform/resolvers@3.3.4
[11:31:13.862] + @next-auth/prisma-adapter@1.0.7
[11:31:13.862] + @oplayer/core@1.2.36
[11:31:13.862] + @oplayer/hls@1.2.26
[11:31:13.862] + @oplayer/plugins@1.0.13
[11:31:13.862] + @oplayer/react@1.2.10
[11:31:13.862] + @oplayer/torrent@1.2.3
[11:31:13.862] + @oplayer/ui@1.3.3-beta.0
[11:31:13.862] + @prisma/client@5.15.0
[11:31:13.863] + @prisma/extension-accelerate@0.6.3
[11:31:13.863] + @radix-ui/react-alert-dialog@1.0.5
[11:31:13.863] + @radix-ui/react-aspect-ratio@1.0.3
[11:31:13.863] + @radix-ui/react-avatar@1.0.4
[11:31:13.863] + @radix-ui/react-dialog@1.0.5
[11:31:13.863] + @radix-ui/react-dropdown-menu@2.0.6
[11:31:13.863] + @radix-ui/react-icons@1.3.0
[11:31:13.863] + @radix-ui/react-label@2.0.2
[11:31:13.863] + @radix-ui/react-scroll-area@1.0.5
[11:31:13.863] + @radix-ui/react-select@2.0.0
[11:31:13.863] + @radix-ui/react-separator@1.0.3
[11:31:13.864] + @radix-ui/react-slot@1.0.2
[11:31:13.864] + @radix-ui/react-tabs@1.0.4
[11:31:13.864] + @radix-ui/react-tooltip@1.0.7
[11:31:13.864] + @t3-oss/env-nextjs@0.10.1
[11:31:13.864] + @tanstack/react-query@5.35.5
[11:31:13.864] + @tanstack/react-query-devtools@5.35.5
[11:31:13.864] + @types/node@20.6.0
[11:31:13.864] + @types/react@18.2.21
[11:31:13.865] + @types/react-dom@18.2.7
[11:31:13.865] + @upstash/ratelimit@1.1.3
[11:31:13.865] + @upstash/redis@1.30.1
[11:31:13.865] + @vercel/kv@0.2.4
[11:31:13.865] + @vidstack/react@1.11.24
[11:31:13.865] + artplayer@5.1.1
[11:31:13.865] + artplayer-plugin-hls-quality@2.0.0
[11:31:13.865] + axios@1.6.8
[11:31:13.866] + bcrypt@5.1.1
[11:31:13.866] + class-variance-authority@0.7.0
[11:31:13.866] + clsx@2.1.1
[11:31:13.866] + cmdk@0.2.1
[11:31:13.866] + dayjs@1.11.11
[11:31:13.866] + framer-motion@10.18.0
[11:31:13.866] + geist@1.3.0
[11:31:13.866] + hls.js@1.5.11
[11:31:13.866] + holy-loader@2.3.1
[11:31:13.866] + ioredis@5.4.1
[11:31:13.866] + media-icons@1.1.4
[11:31:13.866] + next@14.2.3
[11:31:13.866] + next-auth@5.0.0-beta.19
[11:31:13.866] + next-pwa@5.6.0
[11:31:13.866] + next-themes@0.2.1
[11:31:13.866] + nextjs-toploader@1.6.12
[11:31:13.866] + rate-limiter-flexible@3.0.6
[11:31:13.867] + react@18.2.0
[11:31:13.867] + react-dom@18.2.0
[11:31:13.867] + react-hook-form@7.51.4
[11:31:13.867] + react-icons@4.12.0
[11:31:13.867] + react-intersection-observer@9.10.3
[11:31:13.867] + react-textarea-autosize@8.5.3
[11:31:13.867] + server-only@0.0.1
[11:31:13.867] + sharp@0.32.6
[11:31:13.867] + sonner@1.4.41
[11:31:13.867] + swiper@10.3.1
[11:31:13.867] + swr@2.2.5
[11:31:13.867] + tailwind-merge@1.14.0
[11:31:13.867] + tailwindcss-animate@1.0.7
[11:31:13.867] + typescript@5.2.2
[11:31:13.867] + vidstack@0.6.15
[11:31:13.867] + zod@3.23.8
[11:31:13.867] + zustand@4.4.1
[11:31:13.867] 
[11:31:13.868] 1067 packages installed [12.96s]
[11:31:13.868] 
[11:31:13.868] Blocked 2 postinstalls. Run `bun pm untrusted` for details.
[11:31:13.899] Detected Next.js version: 14.2.3
[11:31:13.905] Running "bun run build"
[11:31:13.911] $ next build
[11:31:14.548] ❌ Invalid environment variables: {
[11:31:14.548]   UPSTASH_REDIS_REST_URL: [ 'Required' ],
[11:31:14.548]   UPSTASH_REDIS_REST_TOKEN: [ 'Required' ]
[11:31:14.548] }
[11:31:14.549]  ⨯ Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
[11:31:14.556] 
[11:31:14.557] > Build error occurred
[11:31:14.558] Error: Invalid environment variables
[11:31:14.558]     at onValidationError (file:///vercel/path0/node_modules/@t3-oss/env-core/dist/index.js:29:15)
[11:31:14.558]     at createEnv (file:///vercel/path0/node_modules/@t3-oss/env-core/dist/index.js:35:16)
[11:31:14.558]     at createEnv (file:///vercel/path0/node_modules/@t3-oss/env-nextjs/dist/index.js:12:12)
[11:31:14.558]     at file:///vercel/path0/src/env.mjs:4:20
[11:31:14.559]     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
[11:31:14.559]     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
[11:31:14.559]     at async loadConfig (/vercel/path0/node_modules/next/dist/server/config.js:698:36)
[11:31:14.559]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20)
[11:31:14.559]     at async /vercel/path0/node_modules/next/dist/build/index.js:372:28
[11:31:14.559]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20)
[11:31:14.568] error: script "build" exited with code 1
[11:31:14.574] Error: Command "bun run build" exited with 1
[11:31:15.190]

**Comment by skgupta507** [comment]
> Hi, do you know what might be causing this?
> 
> [11:30:56.864] Running build in Washington, D.C., USA (East) – iad1 [11:30:57.051] Cloning github.com/InstaTechHD/animehi-stream (Branch: master, Commit: [fb7a3a5](https://github.com/benjoquilario/animehi-stream/commit/fb7a3a50bdd4acf8e1886efa8862bbbf7b314525)) [11:30:57.557] Previous build cache not available [11:30:58.483] Cloning completed: 1.431s [11:30:59.346] Running "vercel build" [11:31:00.305] Vercel CLI 35.1.0 [11:31:00.880] Installing dependencies... [11:31:00.926] bun install v1.1.17 (bb66bba1) [11:31:00.945] Resolving dependencies [11:31:00.993] Resolved, downloaded and extracted [2] [11:31:12.392] Saved lockfile [11:31:12.392] [11:31:12.392] $ prisma generate [11:31:12.924] Prisma schema loaded from prisma/schema.prisma [11:31:13.673] [11:31:13.674] ✔ Generated Prisma Client (v5.15.0) to ./node_modules/@prisma/client in 229ms [11:31:13.675] [11:31:13.675] Start using Prisma Client in Node.js (See: https://pris.ly/d/client) [11:31:13.675] `[11:31:13.675] import { PrismaClient } from '@prisma/client' [11:31:13.675] const prisma = new PrismaClient() [11:31:13.675]` [11:31:13.676] or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate) [11:31:13.676] `[11:31:13.676] import { PrismaClient } from '@prisma/client/edge' [11:31:13.676] const prisma = new PrismaClient() [11:31:13.676]` [11:31:13.677] [11:31:13.677] See other ways of importing Prisma Client: http://pris.ly/d/importing-client [11:31:13.677] [11:31:13.677] ┌─────────────────────────────────────────────────────────────┐ [11:31:13.677] │ Deploying your app to serverless or edge functions? │ [11:31:13.678] │ Try Prisma Accelerate for connection pooling and caching. │ [11:31:13.678] │ https://pris.ly/cli/--accelerate │ [11:31:13.678] └─────────────────────────────────────────────────────────────┘ [11:31:13.678] [11:31:13.860] [11:31:13.860] + @ianvs/prettier-plugin-sort-imports@4.2.1 [11:31:13.860] + @tanstack/eslint-plugin-query@5.32.1 [11:31:13.860] + @types/bcrypt@5.0.2 [11:31:13.860] + @types/lodash.chunk@4.2.9 [11:31:13.860] + @typescript-eslint/parser@6.21.0 [11:31:13.861] + autoprefixer@10.4.15 [11:31:13.861] + eslint@8.49.0 [11:31:13.861] + eslint-config-next@13.4.19 [11:31:13.861] + eslint-config-prettier@9.1.0 [11:31:13.861] + eslint-plugin-import@2.29.1 [11:31:13.861] + eslint-plugin-prettier@5.1.3 [11:31:13.861] + eslint-plugin-react@7.34.1 [11:31:13.861] + eslint-plugin-react-hooks@4.6.2 [11:31:13.861] + eslint-plugin-simple-import-sort@12.1.0 [11:31:13.861] + eslint-plugin-tailwindcss@3.15.2 [11:31:13.861] + eslint-plugin-unused-imports@3.2.0 [11:31:13.861] + lodash.chunk@4.2.0 [11:31:13.861] + postcss@8.4.29 [11:31:13.861] + prettier@3.2.5 [11:31:13.861] + prettier-plugin-tailwindcss@0.5.14 [11:31:13.861] + prisma@5.15.0 [11:31:13.862] + tailwindcss@3.3.3 [11:31:13.862] + @auth/core@0.16.1 [11:31:13.862] + @auth/prisma-adapter@2.2.0 [11:31:13.862] + @consumet/extensions@1.5.6 [11:31:13.862] + @hookform/resolvers@3.3.4 [11:31:13.862] + @next-auth/prisma-adapter@1.0.7 [11:31:13.862] + @oplayer/core@1.2.36 [11:31:13.862] + @oplayer/hls@1.2.26 [11:31:13.862] + @oplayer/plugins@1.0.13 [11:31:13.862] + @oplayer/react@1.2.10 [11:31:13.862] + @oplayer/torrent@1.2.3 [11:31:13.862] + @oplayer/ui@1.3.3-beta.0 [11:31:13.862] + @prisma/client@5.15.0 [11:31:13.863] + @prisma/extension-accelerate@0.6.3 [11:31:13.863] + @radix-ui/react-alert-dialog@1.0.5 [11:31:13.863] + @radix-ui/react-aspect-ratio@1.0.3 [11:31:13.863] + @radix-ui/react-avatar@1.0.4 [11:31:13.863] + @radix-ui/react-dialog@1.0.5 [11:31:13.863] + @radix-ui/react-dropdown-menu@2.0.6 [11:31:13.863] + @radix-ui/react-icons@1.3.0 [11:31:13.863] + @radix-ui/react-label@2.0.2 [11:31:13.863] + @radix-ui/react-scroll-area@1.0.5 [11:31:13.863] + @radix-ui/react-select@2.0.0 [11:31:13.863] + @radix-ui/react-separator@1.0.3 [11:31:13.864] + @radix-ui/react-slot@1.0.2 [11:31:13.864] + @radix-ui/react-tabs@1.0.4 [11:31:13.864] + @radix-ui/react-tooltip@1.0.7 [11:31:13.864] + @t3-oss/env-nextjs@0.10.1 [11:31:13.864] + @tanstack/react-query@5.35.5 [11:31:13.864] + @tanstack/react-query-devtools@5.35.5 [11:31:13.864] + @types/node@20.6.0 [11:31:13.864] + @types/react@18.2.21 [11:31:13.865] + @types/react-dom@18.2.7 [11:31:13.865] + @upstash/ratelimit@1.1.3 [11:31:13.865] + @upstash/redis@1.30.1 [11:31:13.865] + @vercel/kv@0.2.4 [11:31:13.865] + @vidstack/react@1.11.24 [11:31:13.865] + artplayer@5.1.1 [11:31:13.865] + artplayer-plugin-hls-quality@2.0.0 [11:31:13.865] + axios@1.6.8 [11:31:13.866] + bcrypt@5.1.1 [11:31:13.866] + class-variance-authority@0.7.0 [11:31:13.866] + clsx@2.1.1 [11:31:13.866] + cmdk@0.2.1 [11:31:13.866] + dayjs@1.11.11 [11:31:13.866] + framer-motion@10.18.0 [11:31:13.866] + geist@1.3.0 [11:31:13.866] + hls.js@1.5.11 [11:31:13.866] + holy-loader@2.3.1 [11:31:13.866] + ioredis@5.4.1 [11:31:13.866] + media-icons@1.1.4 [11:31:13.866] + next@14.2.3 [11:31:13.866] + next-auth@5.0.0-beta.19 [11:31:13.866] + next-pwa@5.6.0 [11:31:13.866] + next-themes@0.2.1 [11:31:13.866] + nextjs-toploader@1.6.12 [11:31:13.866] + rate-limiter-flexible@3.0.6 [11:31:13.867] + react@18.2.0 [11:31:13.867] + react-dom@18.2.0 [11:31:13.867] + react-hook-form@7.51.4 [11:31:13.867] + react-icons@4.12.0 [11:31:13.867] + react-intersection-observer@9.10.3 [11:31:13.867] + react-textarea-autosize@8.5.3 [11:31:13.867] + server-only@0.0.1 [11:31:13.867] + sharp@0.32.6 [11:31:13.867] + sonner@1.4.41 [11:31:13.867] + swiper@10.3.1 [11:31:13.867] + swr@2.2.5 [11:31:13.867] + tailwind-merge@1.14.0 [11:31:13.867] + tailwindcss-animate@1.0.7 [11:31:13.867] + typescript@5.2.2 [11:31:13.867] + vidstack@0.6.15 [11:31:13.867] + zod@3.23.8 [11:31:13.867] + zustand@4.4.1 [11:31:13.867] [11:31:13.868] 1067 packages installed [12.96s] [11:31:13.868] [11:31:13.868] Blocked 2 postinstalls. Run `bun pm untrusted` for details. [11:31:13.899] Detected Next.js version: 14.2.3 [11:31:13.905] Running "bun run build" [11:31:13.911] $ next build [11:31:14.548] ❌ Invalid environment variables: { [11:31:14.548] UPSTASH_REDIS_REST_URL: [ 'Required' ], [11:31:14.548] UPSTASH_REDIS_REST_TOKEN: [ 'Required' ] [11:31:14.548] } [11:31:14.549] ⨯ Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error [11:31:14.556] [11:31:14.557] > Build error occurred [11:31:14.558] Error: Invalid environment variables [11:31:14.558] at onValidationError (file:///vercel/path0/node_modules/@t3-oss/env-core/dist/index.js:29:15) [11:31:14.558] at createEnv (file:///vercel/path0/node_modules/@t3-oss/env-core/dist/index.js:35:16) [11:31:14.558] at createEnv (file:///vercel/path0/node_modules/@t3-oss/env-nextjs/dist/index.js:12:12) [11:31:14.558] at file:///vercel/path0/src/env.mjs:4:20 [11:31:14.559] at ModuleJob.run (node:internal/modules/esm/module_job:222:25) [11:31:14.559] at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) [11:31:14.559] at async loadConfig (/vercel/path0/node_modules/next/dist/server/config.js:698:36) [11:31:14.559] at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20) [11:31:14.559] at async /vercel/path0/node_modules/next/dist/build/index.js:372:28 [11:31:14.559] at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20) [11:31:14.568] error: script "build" exited with code 1 [11:31:14.574] Error: Command "bun run build" exited with 1 [11:31:15.190]

hey @InstaTechHD ur missing the UPstash variables
**❌ Invalid environment variables: {
[11:31:14.548] UPSTASH_REDIS_REST_URL: [ 'Required' ],
[11:31:14.548] UPSTASH_REDIS_REST_TOKEN: [ 'Required' ]**

add these and it will deploy without any issue.
